HOSTS:
  centos-7-64-1:
    roles:
      - master
      - dashboard
      - database
      - agent
    vmname: centos-7-x86-64-west
    platform: el-7-x86_64
    hypervisor: ec2
    amisize: t2.micro
    snapshot: foss
CONFIG:
  nfs_server: none
  consoleport: 443
