HOSTS:
  centos-5-64-1:
    roles:
      - master
      - dashboard
      - database
      - agent
    vmname: centos-5-x86-64-west
    platform: el-5-x86_64
    hypervisor: ec2
    snapshot: foss
    user: ec2-user
