HOSTS:
  ubuntu-1404-x64:
    roles:
      - master
      - agent
      - dashboard
      - cloudpro
    platform: ubuntu-1204-x86_64
    hypervisor: vagrant
    box: hashicorp/precise32
    box_url: https://atlas.hashicorp.com/hashicorp/boxes/precise32
CONFIG:
  nfs_server: none
  consoleport: 443
  type: foss
 
